# Numpy


In [1]:
import numpy as np

In [2]:
#1-@ array
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
#2-D array
b=np.array([[1.,1.],[1.,1.]])
b

array([[1., 1.],
       [1., 1.]])

In [5]:
c=np.array([1,2,3],dtype="int16")

In [6]:
print(a)
print(b)
print(c)

[1 2 3]
[[1. 1.]
 [1. 1.]]
[1 2 3]


In [7]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int16


In [8]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
# returns the dimensions of the array

1
2
1


In [9]:
print(a.shape)
print(b.shape)
print(c.shape)
# returns the number of rows and columns for the arrays

(3,)
(2, 2)
(3,)


In [10]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
# returns the memory size allocated to the item in bytes

4
8
2


In [11]:
print(a.size)
print(b.size)
print(c.size)
# returns the number of elements in the array

3
4
3


In [12]:
print(b.size * b.itemsize)

32


In [13]:
arr = [range(1,5)]
np.array(arr)

array([[1, 2, 3, 4]])

In [14]:
arr = [range(1,5),range(5,9)]
np.array(arr)
# range function returns a list within the range. Here, range() 
# is used to create 2 nested lists and convert them to a numpy 2-D array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
z=np.array(np.arange(24))
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
z = np.arange(24)

In [18]:
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [20]:
np.array(np.arange(24)).reshape(3,8)
# reshape() is used to shape the matrix into the desired
# number of rows and columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [21]:
np.array(np.arange(24)).reshape(2,3,4)
# here the first parameter of reshape is the z-axis, 2nd parameter is the y-axis,
# 3rd parameter is the z-axis

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
y=np.array(np.arange(24)).reshape(2,3,4) * 10 + 3

In [23]:
print(y)

[[[  3  13  23  33]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[123 133 143 153]
  [163 173 183 193]
  [203 213 223 233]]]


In [25]:
d = np.array(np.arange(24)).reshape(2,3,4)
e = np.array(np.arange(24)).reshape(2,3,4) *10+3
np.append(d,e,axis=0)
# joining 2 matrices along the z-axis (along width)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [29]:
np.append(d,e,axis=1)
# joining 2 matrices along the y-axis (along rows)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [30]:
np.append(d,e,axis=2)
# joining 2 matrices along the x-axis (along columns)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [31]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [32]:
a[1,5]

13

In [33]:
a[1][5]

13

In [34]:
a[1][-2]
# reverse indexing always starts from -1, and normal
# indexing starts from 0

13

In [35]:
a[0:1,0:3]
# slicing a 2-D array into different ranges and getting different
# sub-arrays

array([[1, 2, 3]])

In [44]:
a[0:a.shape[0],0:3]

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [37]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [38]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
a[:,2]

array([ 3, 10])

# Pandas

In [45]:
import numpy as np
import pandas as pd

In [46]:
o1=pd.Series([4,7,-5,3])
o1

0    4
1    7
2   -5
3    3
dtype: int64

In [47]:
o1.values

array([ 4,  7, -5,  3], dtype=int64)

In [48]:
o2=pd.Series([4,7,-5,3], index=['d','k','c','a'])
o2
# by default the type here is int64

d    4
k    7
c   -5
a    3
dtype: int64

In [49]:
o4=pd.Series([1,"Gaurav",3.5,"Aviral"])
o4

0         1
1    Gaurav
2       3.5
3    Aviral
dtype: object

In [50]:
data={"name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],      
      "score":[90,80,85,75,95,60,65],      
      "sport":["Wrestling","Football","Skiing","Swimming","Tennis",
               "Karete","Surfing"],      
      "sex":["M","M","M","M","F","F","F"]}


In [51]:
pd.DataFrame(data)
# for a dictionary to be converted to a dataframe, the number of values in each column has to be the same.

name  score      sport sex
0     Bill     90  Wrestling   M
1      Tom     80   Football   M
2      Tim     85     Skiing   M
3     John     75   Swimming   M
4     Alex     95     Tennis   F
5  Vanessa     60     Karete   F
6     Kate     65    Surfing   F

In [52]:
df = pd.DataFrame(data)

In [53]:
df.head(2)

name  score      sport sex
0  Bill     90  Wrestling   M
1   Tom     80   Football   M

In [54]:
df.tail(2)

name  score    sport sex
5  Vanessa     60   Karete   F
6     Kate     65  Surfing   F

In [55]:
df.head()

name  score      sport sex
0  Bill     90  Wrestling   M
1   Tom     80   Football   M
2   Tim     85     Skiing   M
3  John     75   Swimming   M
4  Alex     95     Tennis   F

In [58]:
pd.DataFrame(data,columns=["name","score","sport","sex","age"])

name  score      sport sex  age
0     Bill     90  Wrestling   M  NaN
1      Tom     80   Football   M  NaN
2      Tim     85     Skiing   M  NaN
3     John     75   Swimming   M  NaN
4     Alex     95     Tennis   F  NaN
5  Vanessa     60     Karete   F  NaN
6     Kate     65    Surfing   F  NaN

In [59]:
print(df)

      name  score      sport sex  age
0     Bill     90  Wrestling   M  NaN
1      Tom     80   Football   M  NaN
2      Tim     85     Skiing   M  NaN
3     John     75   Swimming   M  NaN
4     Alex     95     Tennis   F  NaN
5  Vanessa     60     Karete   F  NaN
6     Kate     65    Surfing   F  NaN


In [60]:
df["sport"]

0    Wrestling
1     Football
2       Skiing
3     Swimming
4       Tennis
5       Karete
6      Surfing
Name: sport, dtype: object

In [61]:
df1=["sport","name"]


In [62]:
df[df1]

sport     name
0  Wrestling     Bill
1   Football      Tom
2     Skiing      Tim
3   Swimming     John
4     Tennis     Alex
5     Karete  Vanessa
6    Surfing     Kate

In [63]:
df["age"]=30
df

name  score      sport sex  age
0     Bill     90  Wrestling   M   30
1      Tom     80   Football   M   30
2      Tim     85     Skiing   M   30
3     John     75   Swimming   M   30
4     Alex     95     Tennis   F   30
5  Vanessa     60     Karete   F   30
6     Kate     65    Surfing   F   30